import { StyleSheet,Dimensions } from "react-native"

export const UsersToCourseScreenStyle = StyleSheet.create({
    titleContainer:{
        display:'flex',
        flexDirection:'row',
        top:45,
    },
    titleContainer2:{
        display:'flex',
        flexDirection:'row',
        top:10,

    },
    icon:{
        left:10,
        marginRight:'auto',
        position:'absolute',
        zIndex:10
    },
    title1:{
        flex:1,
        color:'white',
        textAlign:'center',
        fontWeight:'bold',
        fontSize:25,
        
    },
    title2:{
        flex:1,
        color:'#009AB9',
        textAlign:'center',
        fontWeight:'bold',
    },
    formContainer:{
        top:Dimensions.get('window').height/2/2,
        width:'90%',
        display:'flex',
        justifyContent:'center',
        left:'5%',
        elevation:15
    },
    formTitle:{
        textAlign:'center',
        fontWeight:'bold',
        fontSize:20,
        color: '#009AB9'
    },
    userContainer:{ 
        borderWidth:1, 
        borderColor:'#009AB9', 
        borderRadius:5, 
        width:'50%', 
        alignSelf:'center', 
        margin:3, 
        padding:1 
    }, 
    userSelectedContainer:{ 
        borderWidth:1, 
        borderColor:'#009AB9', 
        borderRadius:5, 
        backgroundColor:'#009AB9', 
        width:'50%', 
        alignSelf:'center', 
        margin:3, 
        padding:1 
    }, 
    userSelectedTExt:{ 
        fontSize:15, 
        fontWeight:'bold', 
        textAlign:'center', 
        color:'white' 
    }, 
    userText:{ 
        fontSize:15, 
        fontWeight:'bold', 
        textAlign:'center', 
        color:'#009AB9' 
    },
    listContainer:{
        marginTop:200,
        height:400
    },
    listContainer2:{
        height:150,
        top:10
    },
    listTitle:{
        textAlign:'center',
        color:'#009AB9',
        fontWeight:'bold'
    } 
})